### PR TITLE
fix shortcuts, sidebar size, debounce called in every render

### LINKED ISSUE #40: Customize the source field in json export
related issue: https://github.com/excalidraw/excalidraw/issues/5085

### LINKED ISSUE #42: editor shortcuts bubble outside
For example, undo/redo shortcuts (ctrl-z/ctrl-y) also trigger vscode's undo/redo.

`Ctrl-x` to cut doesn't work at all for some reason, though this may be unrelated to this issue.

### PR DESCRIPTION
**Pull request by pomdtr**
fix #42 
fix #40
fix #23

### CODE REVIEW

**Comment by pomdtr** [comment]
The keybinding method is not right. Instead, we should stop the propagation of the `cmd+z`, `cmd+shift+z` and `cmd+x` events

File: webview/src/App.tsx [hunk 1]
```diff
@@ -64,22 +67,85 @@ function useTheme(initialThemeConfig: string) {
   return { theme, setThemeConfig };
 }
 
+const textEncoder = new TextEncoder();
+
+function onChange(initialSceneVersion: number, contentType: string) {
+  let previousSceneVersion = initialSceneVersion;
```
Comment (dwelle) [inline webview/src/App.tsx]: this isn't really `previousSceneVersion` as it will always point to the `initialSceneVersion` (which the `onChange` function will always be called with). Is that intentional?

Comment (pomdtr) [reply webview/src/App.tsx]: I might be wrong, but here is the logic i went with:

- The `onChange` function is called inside a `useRef`, so it will only be called one time.
- it returns a closure, with the `previousSceneVersion` variable set to the `initialSceneVersion`
- each time the closure is called, the `previousSceneVersion` increase

Comment (pomdtr) [reply webview/src/App.tsx]: I agree this is not really readable, any suggestions are welcome ! I mostly struggle on avoiding recalling the `debounce` function on every render.

Comment (pomdtr) [reply webview/src/App.tsx]: I simplified the logic by passing the onChange function directly as a prop in 5a23808

**Review by dwelle — APPROVED** [review]
